language: c

before_install:
  - mkdir -p /tmp/scratch

install:
  - ./tools/install-chibi
  - source ~/.profile
  - ./tools/install-dependencies
  - ./tools/install-self

script:
  - ./tools/run-all-tests
